[package]
name = "nanoserde"
version = "0.1.12"
authors = ["makepad <info@makepad.nl>", "Fedor <not.fl3@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Fork of makepad-tinyserde without any external dependencies."
edition = "2018"
repository = "https://github.com/not-fl3/nanoserde"

[dependencies]
nanoserde-derive = { path = "derive", version = "=0.1.9" }
